# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1
loader_version=0.19.2

# Mod Properties
mod_version=26.1.x-1.0.1
maven_group=net.bandit.better_hp
archives_base_name=better-hp

# Dependencies
fabric_version=0.147.0+26.1.2
modmenu_version=18.0.0-alpha.8
cloth_config_version=26.1.154